name: Zola on GitHub Pages

on:
  push:
    branches:
      - main
  schedule:
    - cron: "50,55 18 * * 6"
jobs:
  build:
    name: Publish site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3.0.0
      - name: Build and deploy
        uses: shalzz/zola-deploy-action@master
        env:
          CHECK_LINKS: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
